apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app
  namespace: argocd
  labels:
    app: weather-app
    environment: dev
  annotations:
    argocd.argoproj.io/reconcile-options: Prune=true
spec:
  project: default
  source:
    repoURL: https://github.com/saniroad4-hub/NEWArgoCICD.git
    targetRevision: master
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: weather-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true